-- Test data for local development. Safe to re-run (idempotent on scraper_key /
-- content_hash).
--
-- The entries below are illustrative fixtures modelled on the shape of real
-- portal listings. They are NOT scraped records -- run the scrapers for those.

-- is_active drives which scrapers the runner picks up.
--   pib, ssc  -> verified working against the live portals
--   raj_eproc -> inactive: every tender listing on the portal is CAPTCHA-gated
--                (see app/scrapers/sources/raj_eproc.py for the evidence and
--                the alternatives). Flip to true once a CAPTCHA-free route exists.
--   cppp      -> inactive: CAPTCHA-gated, same as raj_eproc. Every NIC
--                eProcurement portal (central, UP, Maharashtra, MP) hides its
--                tender list behind "Provide Captcha and click on Search".
INSERT INTO sources (name, url, category, state, scraper_key, frequency_minutes, is_active) VALUES
  ('Press Information Bureau',         'https://pib.gov.in/allRel.aspx?reg=3&lang=1', 'notice', 'ALL', 'pib',        60,  true),
  ('Staff Selection Commission',       'https://ssc.gov.in',                          'naukri', 'ALL', 'ssc',       120,  true),
  ('Government e-Marketplace',         'https://bidplus.gem.gov.in/all-bids',         'tender', 'ALL', 'gem',       120,  true),
  ('National Testing Agency',          'https://www.nta.ac.in/NoticeBoardArchive',    'naukri', 'ALL', 'nta',       180,  true),
  ('State Bank of India',              'https://sbi.co.in/web/careers/current-openings','naukri','ALL', 'sbi',       240,  true),
  ('IBPS CRP Updates',                 'https://www.ibps.in/index.php/crp-updates/',  'naukri', 'ALL', 'ibps_crp',  240,  true),
  ('IBPS Recruitment',                 'https://www.ibps.in/index.php/recruitment/',  'naukri', 'ALL', 'ibps_recruitment', 240, true),
  ('RRB Secunderabad',                 'https://rrb.indianrailways.gov.in/secunderabad','naukri','ALL','rrb_secunderabad', 240, true),
  ('Rajasthan eProcurement',           'https://eproc.rajasthan.gov.in',              'tender', 'RJ',  'raj_eproc',  60,  false),
  ('Central Public Procurement Portal','https://eprocure.gov.in/eprocure/app',        'tender', 'ALL', 'cppp',       60,  false)
ON CONFLICT (scraper_key) DO NOTHING;

INSERT INTO entries (
  source_id, title, summary_en, summary_hi, category, state, department,
  original_url, deadline, published_date, budget_amount, urgency, ai_confidence,
  content_hash, status, published_at, key_details
) VALUES
  ((SELECT id FROM sources WHERE scraper_key='raj_eproc'),
   'Road widening work on Jaipur-Sikar highway, 12 km stretch',
   'The Rajasthan PWD has invited bids to widen a 12 km stretch of the Jaipur-Sikar highway. Estimated cost is Rs 8.4 crore and the EMD is Rs 16.8 lakh. Contractors with Class A registration can apply until the closing date.',
   'राजस्थान PWD ने जयपुर-सीकर हाईवे के 12 किमी हिस्से को चौड़ा करने के लिए टेंडर निकाला है। अनुमानित लागत 8.4 करोड़ रुपये है और EMD 16.8 लाख रुपये है। क्लास A ठेकेदार अंतिम तिथि तक आवेदन कर सकते हैं।',
   'tender', 'RJ', 'Public Works Department',
   'https://eproc.rajasthan.gov.in/nicgep/app?tender=RJ-PWD-2026-0412',
   CURRENT_DATE + 5, CURRENT_DATE - 2, 840000000, 'critical', 0.94,
   'seed_hash_0001', 'approved', NOW() - INTERVAL '2 days',
   '{"emd_amount": 1680000, "tender_id": "RJ-PWD-2026-0412", "helpline": "0141-2385791"}'),

  ((SELECT id FROM sources WHERE scraper_key='ssc'),
   'SSC CGL 2026: 8,326 vacancies announced for graduates',
   'The Staff Selection Commission has announced 8,326 vacancies in the Combined Graduate Level examination 2026. Any graduate aged 18 to 32 can apply. Pay ranges from Rs 25,500 to Rs 81,100 per month depending on the post.',
   'कर्मचारी चयन आयोग ने CGL परीक्षा 2026 में 8,326 पदों की घोषणा की है। 18 से 32 वर्ष का कोई भी स्नातक आवेदन कर सकता है। पद के अनुसार वेतन 25,500 से 81,100 रुपये प्रति माह है।',
   'naukri', 'ALL', 'Staff Selection Commission',
   'https://ssc.gov.in/notice/cgl-2026-notification',
   CURRENT_DATE + 21, CURRENT_DATE - 4, NULL, 'high', 0.97,
   'seed_hash_0002', 'approved', NOW() - INTERVAL '4 days',
   '{"vacancies": 8326, "application_link": "https://ssc.gov.in/apply"}'),

  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'PM Kisan 19th instalment released to 9.8 crore farmers',
   'The government has released the 19th instalment of PM Kisan Samman Nidhi. Rs 2,000 has been credited directly to the bank accounts of 9.8 crore farmers. Farmers who have not received it should complete their eKYC at the nearest CSC.',
   'सरकार ने PM किसान सम्मान निधि की 19वीं किस्त जारी कर दी है। 9.8 करोड़ किसानों के बैंक खाते में सीधे 2,000 रुपये भेजे गए हैं। जिन किसानों को नहीं मिला है वे नजदीकी CSC पर eKYC पूरा करें।',
   'yojana', 'ALL', 'Ministry of Agriculture and Farmers Welfare',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2099431',
   NULL, CURRENT_DATE - 1, 2000000000000, 'medium', 0.96,
   'seed_hash_0003', 'approved', NOW() - INTERVAL '1 day',
   '{"helpline": "155261", "application_link": "https://pmkisan.gov.in"}'),

  ((SELECT id FROM sources WHERE scraper_key='gem'),
   'Supply of 4,200 desktop computers to Uttar Pradesh schools',
   'The UP education department needs 4,200 desktop computers for government schools. The contract is worth about Rs 21 crore. Bids must be submitted on the GeM portal before the closing date.',
   'यूपी शिक्षा विभाग को सरकारी स्कूलों के लिए 4,200 डेस्कटॉप कंप्यूटर चाहिए। यह अनुबंध लगभग 21 करोड़ रुपये का है। बोली अंतिम तिथि से पहले GeM पोर्टल पर जमा करनी होगी।',
   'tender', 'UP', 'Department of Basic Education',
   'https://gem.gov.in/bid/GEM-2026-B-4412907',
   CURRENT_DATE + 12, CURRENT_DATE - 3, 210000000000, 'high', 0.91,
   'seed_hash_0004', 'approved', NOW() - INTERVAL '3 days',
   '{"tender_id": "GEM-2026-B-4412907", "emd_amount": 4200000}'),

  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'New income tax rules for salaried employees from April',
   'Standard deduction for salaried taxpayers rises to Rs 75,000 under the new tax regime from 1 April. Employees do not need to file anything extra; employers will apply the change automatically in TDS calculations.',
   'नई कर व्यवस्था में वेतनभोगी करदाताओं के लिए स्टैंडर्ड डिडक्शन 1 अप्रैल से बढ़कर 75,000 रुपये हो गया है। कर्मचारियों को अलग से कुछ नहीं भरना है, नियोक्ता TDS में यह बदलाव अपने आप लागू करेंगे।',
   'rule', 'ALL', 'Central Board of Direct Taxes',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2099102',
   NULL, CURRENT_DATE - 6, NULL, 'medium', 0.93,
   'seed_hash_0005', 'approved', NOW() - INTERVAL '6 days', '{}'),

  ((SELECT id FROM sources WHERE scraper_key='cppp'),
   'Construction of 60-bed community health centre in Nagpur',
   'The Maharashtra health department has floated a tender for a 60-bed community health centre in Nagpur district. Estimated cost is Rs 14.7 crore with an EMD of Rs 29.4 lakh. Completion period is 18 months.',
   'महाराष्ट्र स्वास्थ्य विभाग ने नागपुर जिले में 60 बेड के सामुदायिक स्वास्थ्य केंद्र के लिए टेंडर निकाला है। अनुमानित लागत 14.7 करोड़ रुपये और EMD 29.4 लाख रुपये है। काम 18 महीने में पूरा करना है।',
   'tender', 'MH', 'Public Health Department',
   'https://eprocure.gov.in/epublish/app?tender=MH-PHD-2026-1180',
   CURRENT_DATE + 18, CURRENT_DATE - 5, 1470000000, 'high', 0.92,
   'seed_hash_0006', 'approved', NOW() - INTERVAL '5 days',
   '{"emd_amount": 2940000, "tender_id": "MH-PHD-2026-1180"}'),

  ((SELECT id FROM sources WHERE scraper_key='ssc'),
   'SSC MTS 2026: 4,887 posts for 10th pass candidates',
   'The Staff Selection Commission is hiring 4,887 Multi-Tasking Staff. Candidates who have passed class 10 and are aged 18 to 25 can apply. Salary is Rs 18,000 to Rs 22,000 per month.',
   'कर्मचारी चयन आयोग 4,887 मल्टी-टास्किंग स्टाफ की भर्ती कर रहा है। 10वीं पास और 18 से 25 वर्ष के उम्मीदवार आवेदन कर सकते हैं। वेतन 18,000 से 22,000 रुपये प्रति माह है।',
   'naukri', 'ALL', 'Staff Selection Commission',
   'https://ssc.gov.in/notice/mts-2026-notification',
   CURRENT_DATE + 3, CURRENT_DATE - 8, NULL, 'critical', 0.95,
   'seed_hash_0007', 'approved', NOW() - INTERVAL '8 days',
   '{"vacancies": 4887}'),

  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'Free coaching scheme for SC and OBC students opens',
   'The social justice ministry is offering free coaching for competitive exams to SC and OBC students whose family income is under Rs 8 lakh a year. Around 3,500 seats are available across empanelled institutes.',
   'सामाजिक न्याय मंत्रालय SC और OBC छात्रों को प्रतियोगी परीक्षाओं की मुफ्त कोचिंग दे रहा है, जिनकी पारिवारिक आय 8 लाख रुपये सालाना से कम है। सूचीबद्ध संस्थानों में लगभग 3,500 सीटें हैं।',
   'yojana', 'ALL', 'Ministry of Social Justice and Empowerment',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2098877',
   CURRENT_DATE + 40, CURRENT_DATE - 7, NULL, 'low', 0.89,
   'seed_hash_0008', 'approved', NOW() - INTERVAL '7 days',
   '{"application_link": "https://coaching.dosje.gov.in", "vacancies": 3500}'),

  ((SELECT id FROM sources WHERE scraper_key='raj_eproc'),
   'Solar pump subsidy for farmers in Jodhpur division',
   'Rajasthan is offering a 60 percent subsidy on solar water pumps for farmers in Jodhpur division. A 5 HP pump costs about Rs 1.2 lakh after subsidy. Farmers need a Jan Aadhaar card and land records to apply.',
   'राजस्थान जोधपुर संभाग के किसानों को सोलर पंप पर 60 प्रतिशत सब्सिडी दे रहा है। सब्सिडी के बाद 5 HP पंप की कीमत लगभग 1.2 लाख रुपये है। आवेदन के लिए जन आधार कार्ड और जमीन के कागज चाहिए।',
   'yojana', 'RJ', 'Department of Agriculture',
   'https://rajkisan.rajasthan.gov.in/scheme/solar-pump-2026',
   CURRENT_DATE + 25, CURRENT_DATE - 3, NULL, 'medium', 0.90,
   'seed_hash_0009', 'approved', NOW() - INTERVAL '3 days',
   '{"helpline": "0141-2227849"}'),

  ((SELECT id FROM sources WHERE scraper_key='cppp'),
   'Auction of 14 abandoned vehicles by Delhi Police',
   'Delhi Police is auctioning 14 unclaimed vehicles seized over the past two years. The auction is open to the public and the base price for two-wheelers starts at Rs 8,000. Inspection is allowed two days before the auction.',
   'दिल्ली पुलिस पिछले दो साल में जब्त 14 लावारिस वाहनों की नीलामी कर रही है। नीलामी सभी के लिए खुली है और दोपहिया वाहनों की बेस कीमत 8,000 रुपये से शुरू है। नीलामी से दो दिन पहले वाहन देखे जा सकते हैं।',
   'auction', 'DL', 'Delhi Police',
   'https://eprocure.gov.in/epublish/app?auction=DL-POL-2026-0071',
   CURRENT_DATE + 9, CURRENT_DATE - 2, NULL, 'high', 0.88,
   'seed_hash_0010', 'approved', NOW() - INTERVAL '2 days', '{}'),

  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'Aadhaar update deadline extended for free online changes',
   'Free online Aadhaar document updates have been extended by six months. Residents can update proof of identity and address at no cost on the myAadhaar portal. Updates at enrolment centres still cost Rs 50.',
   'मुफ्त ऑनलाइन आधार दस्तावेज अपडेट की सुविधा छह महीने बढ़ा दी गई है। myAadhaar पोर्टल पर पहचान और पते का प्रमाण मुफ्त में अपडेट किया जा सकता है। नामांकन केंद्र पर अपडेट के लिए 50 रुपये लगेंगे।',
   'notice', 'ALL', 'Unique Identification Authority of India',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2098120',
   CURRENT_DATE + 170, CURRENT_DATE - 9, NULL, 'low', 0.94,
   'seed_hash_0011', 'approved', NOW() - INTERVAL '9 days',
   '{"application_link": "https://myaadhaar.uidai.gov.in", "helpline": "1947"}'),

  ((SELECT id FROM sources WHERE scraper_key='gem'),
   'Annual maintenance contract for street lights in Indore',
   'Indore Municipal Corporation needs an agency to maintain 42,000 LED street lights for one year. The contract value is around Rs 3.6 crore. Firms with at least three years of experience are eligible.',
   'इंदौर नगर निगम को एक साल तक 42,000 LED स्ट्रीट लाइट के रखरखाव के लिए एजेंसी चाहिए। अनुबंध की राशि लगभग 3.6 करोड़ रुपये है। कम से कम तीन साल का अनुभव रखने वाली फर्में पात्र हैं।',
   'tender', 'MP', 'Indore Municipal Corporation',
   'https://gem.gov.in/bid/GEM-2026-B-4390122',
   CURRENT_DATE + 6, CURRENT_DATE - 4, 36000000000, 'critical', 0.90,
   'seed_hash_0012', 'approved', NOW() - INTERVAL '4 days',
   '{"emd_amount": 720000, "tender_id": "GEM-2026-B-4390122"}'),

  ((SELECT id FROM sources WHERE scraper_key='ssc'),
   'Railway Recruitment Board: 11,558 technician posts',
   'The Railway Recruitment Board has opened applications for 11,558 technician posts across zones. ITI holders aged 18 to 30 are eligible. Starting pay is Rs 19,900 per month plus allowances.',
   'रेलवे भर्ती बोर्ड ने सभी जोन में 11,558 तकनीशियन पदों के लिए आवेदन शुरू किए हैं। 18 से 30 वर्ष के ITI धारक पात्र हैं। शुरुआती वेतन 19,900 रुपये प्रति माह और भत्ते हैं।',
   'naukri', 'ALL', 'Railway Recruitment Board',
   'https://rrbcdg.gov.in/technician-2026',
   CURRENT_DATE + 15, CURRENT_DATE - 5, NULL, 'high', 0.96,
   'seed_hash_0013', 'approved', NOW() - INTERVAL '5 days',
   '{"vacancies": 11558}'),

  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'Ayushman Bharat now covers all citizens above 70',
   'Everyone aged 70 and above is now covered under Ayushman Bharat regardless of income. The scheme gives Rs 5 lakh of free hospital treatment per family per year. Eligible seniors should register on the PMJAY portal.',
   '70 वर्ष और उससे अधिक आयु के सभी लोग अब आय की परवाह किए बिना आयुष्मान भारत में शामिल हैं। इस योजना में हर परिवार को साल में 5 लाख रुपये तक मुफ्त इलाज मिलता है। पात्र बुजुर्ग PMJAY पोर्टल पर पंजीकरण करें।',
   'yojana', 'ALL', 'Ministry of Health and Family Welfare',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2097655',
   NULL, CURRENT_DATE - 11, NULL, 'medium', 0.95,
   'seed_hash_0014', 'approved', NOW() - INTERVAL '11 days',
   '{"application_link": "https://beneficiary.nha.gov.in", "helpline": "14555"}'),

  ((SELECT id FROM sources WHERE scraper_key='raj_eproc'),
   'Drinking water pipeline for 38 villages in Barmer',
   'The Rajasthan water department has invited tenders to lay a drinking water pipeline serving 38 villages in Barmer district. Estimated cost is Rs 22.5 crore and work must be completed in 24 months.',
   'राजस्थान जल विभाग ने बाड़मेर जिले के 38 गांवों में पेयजल पाइपलाइन बिछाने के लिए टेंडर निकाला है। अनुमानित लागत 22.5 करोड़ रुपये है और काम 24 महीने में पूरा करना है।',
   'tender', 'RJ', 'Public Health Engineering Department',
   'https://eproc.rajasthan.gov.in/nicgep/app?tender=RJ-PHED-2026-0908',
   CURRENT_DATE + 30, CURRENT_DATE - 1, 2250000000, 'medium', 0.93,
   'seed_hash_0015', 'approved', NOW() - INTERVAL '1 day',
   '{"emd_amount": 4500000, "tender_id": "RJ-PHED-2026-0908"}'),

  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'New traffic fine rates take effect across Karnataka',
   'Karnataka has revised traffic penalty amounts. Riding without a helmet now costs Rs 1,000 and driving without insurance costs Rs 2,000. Repeat offences within a year attract double the fine.',
   'कर्नाटक ने ट्रैफिक जुर्माने की राशि बदल दी है। बिना हेलमेट चलाने पर अब 1,000 रुपये और बिना बीमा गाड़ी चलाने पर 2,000 रुपये जुर्माना है। एक साल में दोबारा गलती करने पर जुर्माना दोगुना होगा।',
   'rule', 'KA', 'Transport Department',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2097201',
   NULL, CURRENT_DATE - 13, NULL, 'low', 0.91,
   'seed_hash_0016', 'approved', NOW() - INTERVAL '13 days', '{}'),

  ((SELECT id FROM sources WHERE scraper_key='cppp'),
   'Bihar to hire 2,100 contractual health workers',
   'The Bihar health society is recruiting 2,100 ANMs and lab technicians on contract. Diploma holders aged 21 to 42 can apply. The monthly honorarium is Rs 24,000.',
   'बिहार स्वास्थ्य समिति 2,100 ANM और लैब टेक्नीशियन की संविदा पर भर्ती कर रही है। 21 से 42 वर्ष के डिप्लोमा धारक आवेदन कर सकते हैं। मासिक मानदेय 24,000 रुपये है।',
   'naukri', 'BR', 'State Health Society Bihar',
   'https://statehealthsocietybihar.org/recruitment-2026',
   CURRENT_DATE + 11, CURRENT_DATE - 2, NULL, 'high', 0.87,
   'seed_hash_0017', 'approved', NOW() - INTERVAL '2 days',
   '{"vacancies": 2100}'),

  -- Two low-confidence rows so the admin review queue has something to show.
  ((SELECT id FROM sources WHERE scraper_key='pib'),
   'Corrigendum regarding notification dated 14.03.2026',
   'A correction has been issued to an earlier notification. The details of what changed are unclear from the source text.',
   'पहले जारी अधिसूचना में सुधार किया गया है। स्रोत से यह स्पष्ट नहीं है कि क्या बदला है।',
   'notice', 'ALL', 'Ministry of Finance',
   'https://pib.gov.in/PressReleasePage.aspx?PRID=2099998',
   NULL, CURRENT_DATE, NULL, 'low', 0.42,
   'seed_hash_0018', 'pending', NULL, '{}'),

  ((SELECT id FROM sources WHERE scraper_key='gem'),
   'Bid document for miscellaneous office supplies',
   'A tender has been floated for assorted office supplies. Quantity and estimated value were not stated in the listing.',
   'विविध कार्यालय सामग्री के लिए टेंडर निकाला गया है। सूची में मात्रा और अनुमानित मूल्य नहीं दिया गया है।',
   'tender', 'ALL', 'Government e-Marketplace',
   'https://gem.gov.in/bid/GEM-2026-B-4400018',
   CURRENT_DATE + 14, CURRENT_DATE, NULL, 'low', 0.55,
   'seed_hash_0019', 'pending', NULL, '{}')
ON CONFLICT (content_hash) DO NOTHING;
