import Link from "next/link";

export function Footer() {
  return (
    <footer className="mt-20 border-t border-border">
      <div className="mx-auto max-w-5xl px-4 py-10">
        <div className="flex flex-wrap items-start justify-between gap-8">
          <div className="max-w-sm">
            <div className="text-lg font-extrabold">
              Sarkari<span className="text-primary">Saar</span>
            </div>
            <p className="mt-2 text-xs leading-relaxed text-faint">
              Government notifications in plain language — English and Hindi.
            </p>
          </div>

          <nav className="flex gap-10 text-sm">
            <div className="space-y-2">
              <div className="text-xs font-semibold uppercase tracking-wide text-faint">
                Browse
              </div>
              <Link href="/feed" className="block text-muted hover:text-ink">
                All updates
              </Link>
              <Link
                href="/feed?category=tender"
                className="block text-muted hover:text-ink"
              >
                Tenders
              </Link>
              <Link
                href="/feed?category=naukri"
                className="block text-muted hover:text-ink"
              >
                Jobs
              </Link>
            </div>
            <div className="space-y-2">
              <div className="text-xs font-semibold uppercase tracking-wide text-faint">
                Account
              </div>
              <Link href="/pricing" className="block text-muted hover:text-ink">
                Pricing
              </Link>
              <Link href="/auth/login" className="block text-muted hover:text-ink">
                Sign in
              </Link>
            </div>
          </nav>
        </div>

        <p className="mt-10 border-t border-border pt-6 text-xs leading-relaxed text-faint">
          SarkariSaar is an independent service. It is not affiliated with, endorsed
          by, or operated by any government body. Summaries are generated by AI from
          publicly available notifications and may contain errors — always confirm
          details on the official source before acting on them.
        </p>
      </div>
    </footer>
  );
}
